### ISSUE TITLE
I executed Super Patcher on Mavic Pro (FW v01.03.0700) now I can't connect with DUMLdore

### ISSUE THREAD

**Issue by uLightMe** [brett8883/DJI_Super-Patcher#113]
- I can't connect to PC Windows 10 (tried on multiple computers)
- I can't connect to the RC Remote
- Mavic has a solid RED light on the front and fast blinking yellow on the rear

When plugged into the computer my Mavic Pro seems to be stuck in a boot loop constantly showing connected/disconnected in device manager with (Unknown Device)

I know I screwed up by running Super Patcher on the wrong firmware, but is there anything I can do now to get my Mavic working?

Thank you.

**Comment by axemanarb** [comment]
Try use dumbldore and flash the old firmware back a few times ? Maybe ?

**Comment by uLightMe** [comment]
I can't connect to the PC with a USB cable because it (connects and disconnects) constantly.
Dumbldore doesn't recognize the drone.  
The drone shows up as "Unknown Device" in device manager.

**Comment by axemanarb** [comment]
I know I flashed my p3a with an sd card im not sure if the mavic is the same . Does it show what firmware your on in your app ? Btw im a total newbie so dont take my advise im sure someone will help you fix it @brett8883  ???

**Comment by axemanarb** [comment]
Wait till you get the pro advise first before do anything

**Comment by uLightMe** [comment]
> 
> 
> Wait till you get the pro advise first before do anything

I appreciate you trying to help.  I hope someone here can help me.

**Comment by axemanarb** [comment]
Does it connect to the app and show what firmware your on?

**Comment by axemanarb** [comment]
http://dankdronedownloader.com/DDD2/app/index.php?cat=Mavic%20Pro%201%20-%20Incl%20Platinum%20and%20Alpine

**Comment by uLightMe** [comment]
No. 
I recorded a video of what's happening when I connect it to the computer.
https://youtu.be/TkJi6n9KYxg

**Comment by uLightMe** [comment]
it keeps doing the connect/disconnect (Unknown Device) constantly without an end.

**Comment by uLightMe** [comment]
GOOD NEWS!
After restarting my Mavic for 5 or 6th time and letting it sit there doing what you see in the video for a while.  It now connects to the computer fine and I can flash the correct firmware :) whooohooo.

It would seem like whatever I did before got it stuck in this repeating boot loop during which it was "healing itself" LOL .... finally it turned on and I can connect with DUMLdore again.
