### ISSUE TITLE
downgrade mavic pro 1

### ISSUE THREAD

**Issue by gppms** [brett8883/DJI_Super-Patcher#118]
hello i 'm trying to downgrade the firmware of my mavic pro 1 with the DUMLdore from 01.04.300 downgrade to 01.03.700 and i'm stuck to 01.04.000 and it's not downgrade from there. Can anyone help me?

**Comment by brett8883** [comment]
This doesn’t have anything to do with Super-Patcher. There’s no reason to downgrade that far
