### ISSUE TITLE
DJI Assistant 2 1.1.2

### ISSUE THREAD

**Issue by shlyahten** [brett8883/DJI_Super-Patcher#156]
Hello! Anyone have a working link to download DJI Assistant 2 1.1.2?
Thanks

**Comment by Weirdoz** [comment]
send me your email and i`ll give you a link

**Comment by shlyahten** [comment]
> send me your email and i`ll give you a link. I`ll send a link to your .ru mailaddress
Nikita (at) shlyahten.ru 
Thanks!
