### ISSUE TITLE
Spark features of the Super Patcher ?

### ISSUE THREAD

**Issue by webvan1999** [brett8883/DJI_Super-Patcher#38]
Not really an issue and sorry if I'm a bit slow on the uptake but I just wanted to clarify what impact the MOD had on the Spark, i.e. are all the features listed in the readme work on the Spark ? I'm guessing they do since the Spark is only called out specifically for the FCC MOD (some are having issues with that but there is a separate thread for that).

Namely : 
"Remove height limitations
Remove NFZ and GeoZone limits
Enable Galileo satellite reception
Precision RTH and Precision Landing will work normally
Optionally enable slower more cinematic panning (yaw) speed"

THanks !

**Comment by brett8883** [comment]
Yes all features apply to Spark.
