### ISSUE TITLE
There is a problem on the Spark side

### ISSUE THREAD

**Issue by aldo962** [brett8883/DJI_Super-Patcher#4]
Your Super Patcher can't find the Spark FC file, this is the get request acting bad:
https://github.com/brett8883/Super-Firmware_Cache/raw/master/Spark_Super_Patcher_03.02.44.09_dji_sytem.bin
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

**Comment by brett8883** [comment]
Thanks. Bug has been squashed. Redownload a new copy of 1.5

**Comment by brett8883** [comment]
Issue is resolved. Reopen if still having issues
