### ISSUE TITLE
Yes in Ati mode，but not with GPS，hope to fix it

### ISSUE THREAD

**Issue by yuliang521** [brett8883/DJI_Super-Patcher#53]
Yes in Ati mode，but not with GPS，hope to fix it
姿态模式下会一直上升，有GPS信号就不会

_Originally posted by @yuliang521 in https://github.com/brett8883/DJI_Super-Patcher/issues/39#issuecomment-551086941_

test with my mavic pro Platinum

**Comment by yuliang521** [comment]
sorry for my poor En， my mavic  Platinum keep going up in ati mode ，but RC is working，one little push down and release， it can stay

**Comment by brett8883** [comment]
I am aware of the original issue. There is no need to open new issues and link to the original one.
