### ISSUE TITLE
Spark in patcher 2.02 not working

### ISSUE THREAD

**Issue by elintnl** [brett8883/DJI_Super-Patcher#55]
Hi Brett, 
I saw you update the patcher to version 2.02.
I want to try it on my Spark , but it closed the script.
Thanks in advance.

**Comment by d1ggdugg** [comment]
I have the same problem. The error appears only with the Spark. 

Thank you for your efforts!

**Comment by brett8883** [comment]
I honestly have no idea what happened but I have fixed it now

**Comment by brett8883** [comment]
Closing this issue
