### ISSUE TITLE
Any one Tested on mavic pro 2? 

### ISSUE THREAD

**Issue by tares003** [brett8883/DJI_Super-Patcher#6]
Hi, 

Sorry, it's not a issue. 

Is worth trying on mavic pro 2?

Thanks

**Comment by GrinFactor** [comment]
No it is not supported

**Comment by brett8883** [comment]
Mavic 2 is not supported sorry I’m gonna close this issue but thanks for the interest

**Comment by tares003** [comment]
Any plans on supporting in future?

**Comment by brett8883** [comment]
Somebody needs to figure out a way to get root access and then we are in business but till that happens there’s no way to send commands the the Android System. I don’t have a Mavic 2 so I can’t be the one to figure out how to gain root access unfortunately. :(
