### ISSUE TITLE
mavic pro 1 DUMLdore v3.20 45 min progress

### ISSUE THREAD

**Issue by maulanarizqi** [brett8883/DJI_Super-Patcher#80]
Halo there,
im in step to choose " Please click "load firmware"  button in DUMLdore, ....... then click  flash firmware,

its been more than 45 min and Mavic Pro and the aircraft its off due the insufficient battery   and dumldore progress didnt change into reboot it self what should i do then ?
repeat the process ? 
and how long the process normally take ?

**Comment by brett8883** [comment]
The process shouldn't take longer than 5-6 minutes tops. Most of the time its like 3-4 minutes. 

If the process hangs its usually at the "transferring" stage. The transferring stage should take no longer than 30 seconds. Its usually immediate. If it takes longer than 30 seconds to transfer, close Dumldore, turn off the aircraft, disconnect from computer, take the battery out, wait 10 seconds, ensure there is at least 50% battery remaining (two solid lights and one flashing light minimum), and then try again.
