### ISSUE TITLE
This is not working on the Mavic 2 Pro?

### ISSUE THREAD

**Issue by hydrogenpi** [brett8883/DJI_Super-Patcher#9]
This is not working on the Mavic 2 Pro?

**Comment by brett8883** [comment]
Super-Patcher does not support Mavic 2 yet sorry. We need a way to gain adb access to the Mavic 2 and an encryption key to decrypt the firmware so it can be decompiled. Especially the encryption key is above my pay grade but I don’t have a Mavic 2 to work on. Sorry
