### ISSUE TITLE
Can't fly above 500m

### ISSUE THREAD

**Issue by pointbob** [brett8883/DJI_Super-Patcher#98]
1) I must have done something wrong. I flew to 500m (1640ft) and my RC said MAX ALT REACHED and I couldnt fly higher. I successfly applied super patch just the other day. I checked to make sure the version was correct on NLD as well. Any guess as to what' s going on? i checked dji assist vers 
112 and fly limit height still at 500m  - the others are 3000m...I tried changing the 500m to 3000m but not sticking...

2) how do I know that FCC boost is actually working. I live in a city area and can barely get 1000 ft away when i start losing radio transmission (blinking radio)

![dji param 5209](https://user-images.githubusercontent.com/30416715/77015822-344e0b80-6933-11ea-96f6-17c2095f2e9d.jpg)

**Comment by pointbob** [comment]
repatched a 2nd time and it appears to have worked! thank you

**Comment by brett8883** [comment]
Glad you got it to work. Closing this issue
